#!/bin/bash
#SBATCH -J lsm_new # 8-character name
#SBATCH -o slog # output and error file name (%j expands to jobID)
#SBATCH -e serr
#SBATCH -N 16 # total number of nodes
#SBATCH -n 1024 # total number of mpi tasks requested
#SBATCH -p normal # queue (partition) -- normal, development, etc.
#SBATCH -t 00:30:00 # run time (hh:mm:ss)
#SBATCH -A OTH21032 # Project number
##SBATCH -A A-aoag # Project number

#SBATCH --mail-user=akshit@utexas.edu
#SBATCH --mail-type=end     # email me when the job finishes

echo flat_plate        >  SESSION.NAME
echo `pwd`'/' >>  SESSION.NAME
rm -f logfile
rm -f ioinfo
mv flat_plate.log flat_plate.log1 2>/dev/null
touch flat_plate.log
ln -sf flat_plate.log logfile
ibrun ./nek5000 > flat_plate.log
